# my-project/.github/workflows/terraform.yml
name: Terraform AWS Deployment

on:
  workflow_dispatch: # Enable only manual runs

env:
  TF_WORKING_DIR: ./terraform # working directory for Terraform commands
  AWS_REGION: us-west-2

jobs:
  terraform:
    name: 'Terraform Actions'
    runs-on: ubuntu-latest # Use a fresh Ubuntu runner for each job

    # Permissions for OIDC authentication. Required when using aws-actions/configure-aws-credentials
    permissions:
      id-token: write # This is required for requesting the OIDC token
      contents: read  # This is required for checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # Action to configure AWS credentials using OIDC
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} # IAM Role ARN from GitHub Secrets
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: ${{ env.TF_WORKING_DIR }} # Execute command in the terraform directory

      - name: Install Lambda Dependencies (local-exec step from Terraform)
        id: install_deps
        run: pip install -r "${{ github.workspace }}/src/requirements.txt" -t "${{ github.workspace }}/lambda-code/"
        # This step doesn't run in the TF_WORKING_DIR. It runs at the repo root.

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_region: ${{ env.AWS_REGION }}


      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_region: ${{ env.AWS_REGION }}